// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnimddxwlrkuuwmnkmks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduaW1kZHh3bHJrdXV3bW5rbWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTYyODYsImV4cCI6MjA1ODkzMjI4Nn0.cmQXWHShHahbrATlx2t1cWnF6oFOzQ56UNiLvYF0hCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);